import React, { useEffect, useRef, useState } from 'react';

import { createUseStyles } from 'react-jss';
import { ArrowUpRight, ArrowRight, ArrowLeft, Phone, Menu, X, Check, CheckCheck, MapPin, Sun, Snowflake, Leaf, Home, Layers, Wind, ShieldCheck, ChevronDown, Plus, Minus, Mail, Copy, Wrench, MoveUpRight, Clock3 } from 'lucide-react';


const PHONE = '0466 253 396';
const EMAIL = 'pfinsulation01@gmail.com';
const services = [
  { id: 'removal', title: 'Out with the old.', name: 'Insulation removal', image: 'removal.webp', icon: Wind, text: 'A fresh start for your roof space. We remove old, damaged and unwanted insulation, and clean up what’s left behind.', details: 'From loose-fill cellulose and rockwool to old glasswool batts, we assess the material and roof access before planning removal and disposal.', points: ['Old batts & loose-fill removal', 'Roof-space vacuuming', 'Disposal & clean-up'] },
  { id: 'ceiling', title: 'In with the comfort.', name: 'Ceiling insulation', image: 'ceiling.webp', icon: Home, text: 'Make home feel better, season after season. New insulation, supplied and installed to suit your ceiling space.', details: 'Whether you are replacing tired insulation or insulating for the first time, we can help you choose an appropriate solution. Ask about suitable R5, R6 and R7 options.', points: ['Supply & installation', 'Insulation replacement', 'Options to suit your roof space'] },
  { id: 'underfloor', title: 'Warmth underfoot.', name: 'Underfloor insulation', image: 'underfloor.webp', icon: Layers, text: 'Take the chill out of your floors. Insulate underneath your home for a more comfortable everyday living space.', details: 'We assess access beneath your home and the floor structure to recommend an appropriate underfloor insulation approach.', points: ['Existing-home upgrades', 'Accessible subfloor assessment', 'A more comfortable living space'] },
  { id: 'walls', title: 'Comfort, all around.', name: 'Wall insulation', image: 'wall.webp', icon: ShieldCheck, text: 'Give your home another layer of comfort. Explore insulation options for existing walls and renovation projects.', details: 'Every wall is different. We review its construction and access before discussing suitable installation options, including blow-in insulation where appropriate.', points: ['Existing-wall assessment', 'Renovation projects', 'Property-specific advice'] },
];
const faqs = [
  { category: 'Getting started', q: 'How do I know if my insulation needs replacing?', a: 'Uneven temperatures or insulation that is visibly compressed, damaged or damp can be reasons to have it assessed. We can inspect the roof space and discuss whether removal, replacement or another approach suits your home.' },
  { category: 'Getting started', q: 'Can you remove the old insulation and install new insulation?', a: 'Yes. PF Insulation offers removal, roof-space cleaning, and new insulation supply and installation. Your quote will explain which services are included and any work that needs to be priced separately.' },
  { category: 'Getting started', q: 'Which areas do you service?', a: 'We service Melbourne and surrounding eligible areas of Victoria. Send us your suburb or postcode so we can confirm availability for your property.' },
  { category: 'The process', q: 'How much does insulation cost?', a: 'The price depends on the area, existing material, access, selected insulation and any removal or cleaning needed. Request a free measurement and quote for a price based on your home.' },
  { category: 'The process', q: 'How long does the work take?', a: 'Timing varies with the property and scope of work. Once we have assessed your home, we will discuss the expected schedule and access requirements with you.' },
  { category: 'The process', q: 'Do you offer insulation vacuum hire?', a: 'Yes, vacuum hire is one of our listed services. Contact us to discuss equipment availability, suitability, collection arrangements and hire terms.' },
  { category: 'Rebates', q: 'Could my home qualify for a VEU discount?', a: 'Eligibility depends on the current Victorian Energy Upgrades requirements, the property, existing insulation, safety checks and approval through the applicable Accredited Provider. Contact us for an assessment; an enquiry is not confirmation of a discount.' },
  { category: 'Rebates', q: 'Is PF Insulation a VEU Accredited Provider?', a: 'PF Insulation is an independent insulation contractor. For applicable VEU work, we work with an Accredited Provider. We are not the Victorian Government or the Accredited Provider.' },
];

function Arrow({ className = '' }) { return <ArrowUpRight size={18} className={className} aria-hidden="true" />; }
function Eyebrow({ children, light = false }) { return <div className={`eyebrow ${light ? 'light' : ''}`}><span />{children}</div>; }
function Logo({ footer = false }) { return <a href="#home" className={`brand ${footer ? 'brand-footer' : ''}`} aria-label="PF Insulation home"><img src="/images/logo.jpg" alt="" width="48" height="48" /><div>PF INSULATION<span>COMFORT STARTS WITHIN</span></div></a>; }

function Dialog({ children, onClose, label, className = '' }) {
  const ref = useRef(null);
  useEffect(() => {
    const previous = document.activeElement;
    const dialog = ref.current;
    const oldOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    dialog.showModal();
    return () => { dialog.close(); document.body.style.overflow = oldOverflow; previous?.focus(); };
  }, []);
  return <dialog ref={ref} className={`modal ${className}`} aria-label={label} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) { const r = ref.current.getBoundingClientRect(); if (e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom) onClose(); } }}><button className="modal-close" onClick={onClose} aria-label="Close dialog"><X size={22} /></button>{children}</dialog>;
}

function QuoteDialog({ initialService, onClose }) {
  const [step, setStep] = useState(1);
  const [selected, setSelected] = useState(initialService || '');
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const [details, setDetails] = useState({ name: '', email: '', phone: '', suburb: '', message: '' });
  const stepHeading = useRef(null);
  useEffect(() => { stepHeading.current?.focus(); }, [step]);
  const body = `Hello PF Insulation,\n\nI would like a quote for ${selected}.\n\nName: ${details.name}\nEmail: ${details.email}\nPhone: ${details.phone || 'Not provided'}\nSuburb / postcode: ${details.suburb}\n\n${details.message}\n\nPlease contact me to discuss an assessment.`;
  function update(e) { setDetails({ ...details, [e.target.name]: e.target.value }); }
  return <Dialog onClose={onClose} label="Request a free quote" className="quote-modal">
    <Eyebrow>LET’S MAKE HOME FEEL BETTER</Eyebrow>
    <div className="step-track" aria-label={`Step ${step} of 3`}>{[1,2,3].map(n => <span key={n} className={n <= step ? 'active' : ''} />)}</div>
    <p className="step-label">0{step} / 03 · {step === 1 ? 'YOUR PROJECT' : step === 2 ? 'YOUR DETAILS' : 'YOUR ENQUIRY'}</p>
    <h2 ref={stepHeading} tabIndex={-1}>{step === 1 ? 'What can we help with?' : step === 2 ? 'Tell us a little about you.' : 'Your enquiry is ready.'}</h2>
    {step === 1 && <><p>Choose a service. Not sure? We’ll help you work it out.</p><div className="quote-options">{[...services.map(s => s.name), 'Roof-space cleaning', 'Vacuum hire', 'VEU assessment', 'Not sure yet'].map(s => <button key={s} className={selected === s ? 'selected' : ''} aria-pressed={selected === s} onClick={() => setSelected(s)}>{s}<span>{selected === s && <Check size={14} />}</span></button>)}</div><button className="btn btn-dark w-full" disabled={!selected} onClick={() => setStep(2)}>Continue <ArrowRight size={18} /></button><p className="form-note">Free measurement & quote. No obligation.</p></>}
    {step === 2 && <form onSubmit={e => { e.preventDefault(); setStep(3); }}><p>We’ll use these details to understand your project.</p><div className="form-grid"><label>Your name<input name="name" autoComplete="name" required maxLength={100} value={details.name} onChange={update} placeholder="Full name" /></label><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={150} value={details.email} onChange={update} placeholder="you@example.com" /></label><label>Phone <span>(optional)</span><input name="phone" type="tel" autoComplete="tel" value={details.phone} onChange={update} placeholder="04XX XXX XXX" maxLength={25} /></label><label>Suburb or postcode<input name="suburb" autoComplete="address-level2" required maxLength={100} value={details.suburb} onChange={update} placeholder="e.g. Brunswick, 3056" /></label><label className="full">Anything else? <span>(optional)</span><textarea name="message" rows={3} maxLength={1500} value={details.message} onChange={update} placeholder="Tell us about your home and existing insulation…" /></label></div><p className="form-note text-left">Your details stay in this browser until you choose to send them using your email app.</p><div className="flex gap-3"><button type="button" className="btn btn-outline" onClick={() => setStep(1)}><ArrowLeft size={17} /> Back</button><button type="submit" className="btn btn-dark flex-1">Review enquiry <ArrowRight size={18} /></button></div></form>}
    {step === 3 && <><p>Review your details, then open your email app to send the request to our team.</p><div className="enquiry-review"><span className="mini-label">{selected}</span><strong>{details.name}</strong><span>{details.email} · {details.suburb}</span>{details.phone && <span>{details.phone}</span>}{details.message && <p>{details.message}</p>}</div><a className="btn btn-dark w-full" href={`mailto:${EMAIL}?subject=${encodeURIComponent(`Quote enquiry — ${selected}`)}&body=${encodeURIComponent(body)}`}><Mail size={18} /> Open email to send <Arrow /></a><p className="form-note">Nothing has been sent yet. Send the message from your email app, or copy it and email {EMAIL}.</p><div className="flex flex-wrap justify-between gap-3"><button className="text-button" onClick={() => setStep(2)}><ArrowLeft size={16} /> Edit details</button><button className="text-button" onClick={async () => { try { await navigator.clipboard.writeText(body); setCopied(true); setCopyError(false); } catch { setCopyError(true); } }}>{copied ? <CheckCheck size={16} /> : <Copy size={16} />}{copied ? 'Copied' : 'Copy enquiry'}</button></div><div role="status">{copyError && <p className="form-note">Copy is unavailable in this browser. Use the email button or call {PHONE}.</p>}</div></>}
  </Dialog>;
}

const useComfortStyles = createUseStyles({
  panel: { backgroundColor: ({ isWinter }) => isWinter ? '#e8ede6' : '#f2ecda', transition: 'background-color 400ms ease', borderRadius: 4 },
  icon: { color: ({ isWinter }) => isWinter ? '#436557' : '#92682c', transition: 'color 400ms ease' },
});
function ComfortPanel() {
  const [season, setSeason] = useState('Winter');
  const styles = useComfortStyles({ isWinter: season === 'Winter' });
  return <div className={`comfort-panel ${styles.panel}`}><div className="flex items-center justify-between gap-4"><span className="mini-label">MADE FOR MELBOURNE WEATHER</span><div className="season-tabs" aria-label="Season">{['Winter', 'Summer'].map(s => <button key={s} onClick={() => setSeason(s)} aria-pressed={s === season} className={s === season ? 'active' : ''}>{s === 'Winter' ? <Snowflake size={13} /> : <Sun size={13} />}{s}</button>)}</div></div><div className="comfort-content" aria-live="polite">{season === 'Winter' ? <Snowflake className={styles.icon} size={45} strokeWidth={1} /> : <Sun className={styles.icon} size={45} strokeWidth={1} />}<div><h3>{season === 'Winter' ? 'Keep the warmth where it belongs.' : 'A cooler place to come home to.'}</h3><p>{season === 'Winter' ? 'Help slow heat loss and make your living spaces feel more comfortable.' : 'Help slow heat entering your home, so your spaces feel more comfortable.'}</p></div></div></div>;
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [quote, setQuote] = useState(null);
  const [service, setService] = useState(null);
  const [gallery, setGallery] = useState(null);
  const [faqCategory, setFaqCategory] = useState('Getting started');
  const [faqOpen, setFaqOpen] = useState(faqs[0].q);
  const openQuote = (selected = '') => { setMenuOpen(false); setService(null); setQuote(selected); };
  const menuRef = useRef(null);
  useEffect(() => { if (!menuOpen) return; const close = e => { if (e.key === 'Escape') { setMenuOpen(false); menuRef.current?.focus(); } }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [menuOpen]);
  const nav = [['Services', '#services'], ['Why PF', '#why-pf'], ['Our work', '#our-work'], ['VEU rebates', '#rebates'], ['FAQs', '#faqs']];
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="topbar"><div className="site-container flex items-center justify-between"><span><MapPin size={12} /> Melbourne & surrounding Victoria</span><a href="#rebates">A more efficient home. Explore VEU support. <ArrowRight size={13} /></a></div></div>
    <header className="header"><div className="site-container header-inner"><Logo /><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><div className="header-actions"><a href="tel:0466253396" className="phone-link"><Phone size={15} />{PHONE}</a><button className="btn btn-dark header-quote" onClick={() => openQuote()}>Get a free quote <Arrow /></button><button ref={menuRef} className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div></div>{menuOpen && <nav id="mobile-menu" aria-label="Mobile navigation" className="mobile-menu">{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}<Arrow /></a>)}<button className="btn btn-dark" onClick={() => openQuote()}>Get a free quote <Arrow /></button></nav>}</header>
    <main id="main">
      <section className="hero" id="home"><div className="hero-copy"><Eyebrow>YOUR MELBOURNE INSULATION SPECIALISTS</Eyebrow><h1>Comfort starts<br />from <span>within.</span><span className="heading-period">✳</span></h1><p>A warmer winter. A cooler summer. A home that simply feels better. Thoughtful insulation solutions, from the ground up.</p><div className="hero-buttons"><button className="btn btn-dark" onClick={() => openQuote()}>Find your comfort <Arrow /></button><a href="#services" className="text-link">Explore our services <ArrowRight size={17} /></a></div><div className="hero-reassurance"><span><Check size={14} /> Free measurement & quote</span><span><Check size={14} /> Local Melbourne team</span></div><div className="hero-bottom"><span className="small-mark">PF</span><p>Good for your home.<br /><strong>Better for your everyday.</strong></p><span className="hero-line" /></div></div><div className="hero-image"><img src="/images/comfort.webp" alt="A calm, naturally lit living room with warm neutral furnishings" fetchPriority="high" width="1376" height="768" /><div className="hero-image-top"><span className="image-tag"><span /> COMFORT, IN EVERY SEASON</span><span className="image-location"><MapPin size={13} /> MELBOURNE, VIC</span></div><div className="hero-image-note"><div><Sun size={26} strokeWidth={1.3} /><Snowflake size={26} strokeWidth={1.3} /></div><p>Love the feeling<br />of coming home.</p></div><a href="#services" className="image-scroll" aria-label="Explore insulation services"><ArrowRight size={21} /></a></div></section>
      <section className="benefit-strip" aria-label="Benefits"><div className="site-container grid md:grid-cols-3"><div><Sun /><span>Year-round comfort<small>Whatever Melbourne’s weather brings.</small></span></div><div><Leaf /><span>Smarter energy use<small>Help your home hold its temperature.</small></span></div><div><ShieldCheck /><span>Care in every layer<small>From the first assessment to the finish.</small></span></div></div></section>

      <section id="services" className="section services-section"><div className="site-container"><div className="section-heading"><div><Eyebrow>A LITTLE CHANGE. A BIG DIFFERENCE.</Eyebrow><h2>The right insulation.<br />A better feeling home.</h2></div><p>From removing what’s no longer working to installing what will, we make the next step feel simple.</p></div><div className="service-grid">{services.map((s, i) => <button key={s.id} className="service-card group" onClick={() => setService(s)} aria-label={`Learn about ${s.name}`}><div className="service-image"><img src={`/images/${s.image}`} alt={s.name === 'Insulation removal' ? 'Worker vacuuming old material from a roof space' : s.name === 'Ceiling insulation' ? 'Insulation fitted between timber roof joists' : s.name === 'Underfloor insulation' ? 'Insulation fitted beneath timber flooring' : 'Insulation within a timber wall frame'} loading="lazy" width="600" height="450" /><span className="service-number">0{i + 1}</span><span className="service-arrow"><Arrow /></span></div><div className="service-card-copy"><span className="mini-label">{s.name}</span><h3>{s.title}</h3><p>{s.text}</p></div></button>)}</div><div className="service-extra"><span><Wrench size={18} /> Need roof-space cleaning or insulation vacuum hire?</span><button className="text-link" onClick={() => openQuote('Roof-space cleaning')}>Let’s talk about your project <Arrow /></button></div></div></section>

      <section className="why-section" id="why-pf"><div className="site-container why-grid"><div className="why-visual"><img src="/images/installation.webp" alt="Insulation installation shown at several stages" loading="lazy" width="900" height="616" /><div className="why-caption"><span>THE DIFFERENCE IS IN THE DETAILS</span><ArrowUpRight size={25} /></div><div className="why-stamp"><Layers size={28} strokeWidth={1.3} /><span>Better living.<br />Layer by layer.</span></div></div><div className="why-copy"><Eyebrow light>SMALL TEAM. THOUGHTFUL WORK.</Eyebrow><h2>Your home deserves<br />more than a quick fix.</h2><p>Insulation is something you rarely see, but feel every day. We take the time to understand your home and help you choose what’s right for it.</p><div className="why-values">{[['01', 'A solution for your home', 'Your space, access and existing insulation guide our advice.'], ['02', 'Clarity from the start', 'Understand the work, the options and what’s included in your quote.'], ['03', 'The whole job, considered', 'Removal, cleaning and installation, with the details planned together.']].map(([n, title, text]) => <div key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div><Check size={16} /></div>)}</div><button className="btn btn-lime" onClick={() => openQuote()}>Let’s talk about your home <Arrow /></button></div></div></section>

      <section className="section process-section"><div className="site-container"><div className="section-heading"><div><Eyebrow>LESS GUESSWORK. MORE COMFORT.</Eyebrow><h2>A simple path to<br />a better-insulated home.</h2></div><p>We’ll help you understand what your home needs, one clear step at a time.</p></div><div className="process-grid">{[[Phone, 'Let’s have a chat.', 'Tell us about your home, your suburb and what you’d like to improve.'], [Home, 'A closer look.', 'We assess your space and explain the right options with a clear quote.'], [Layers, 'We get to work.', 'Our team carries out the agreed removal, preparation and installation.'], [Sun, 'Feel the difference.', 'Settle into a home designed to feel more comfortable through the seasons.']].map(([Icon, title, text], i) => <div className="process-step" key={title}><div className="process-step-top"><span>0{i+1}</span><Icon size={24} strokeWidth={1.4} /></div><h3>{title}</h3><p>{text}</p></div>)}</div><ComfortPanel /></div></section>

      <section className="rebate-section" id="rebates"><div className="site-container rebate-grid"><div><span className="pill"><Leaf size={13} /> VICTORIAN ENERGY UPGRADES</span><h2>A little support.<br />A more comfortable home.</h2><p>Your ceiling insulation upgrade may be eligible for support through the VEU program. Let’s explore what’s possible for your property.</p><button className="btn btn-dark" onClick={() => openQuote('VEU assessment')}>Ask about my eligibility <Arrow /></button><a className="rebate-source" href="https://www.energy.vic.gov.au/victorian-energy-upgrades/products/insulation-discounts" target="_blank" rel="noreferrer">Explore official VEU information <ArrowUpRight size={13} /></a></div><div className="rebate-card"><span className="mini-label">A GOOD PLACE TO START</span><h3>Could your home be suitable?</h3>{['Your property is in Victoria', 'Your ceiling has little or no insulation', 'Your roof space can be safely assessed'].map(t => <div className="rebate-check" key={t}><span><Check size={14} /></span>{t}</div>)}<div className="rebate-disclaimer"><ShieldCheck size={18} /><p>Eligibility and discounts depend on current program rules, safety checks and Accredited Provider approval. PF Insulation works with a provider; an enquiry does not guarantee a rebate.</p></div></div></div></section>

      <section className="section work-section" id="our-work"><div className="site-container"><div className="section-heading"><div><Eyebrow>BEHIND THE COMFORT</Eyebrow><h2>Good work. From the inside out.</h2></div><p>A closer look at insulation, roof spaces and the work that makes a difference.</p></div><div className="work-grid">{[['ceiling.webp', 'Ceiling insulation', 'A carefully fitted layer of comfort.'], ['result.webp', 'Roof-space preparation', 'The parts of your home you don’t often see.'], ['removal.webp', 'Insulation removal', 'Making room for a fresh start.']].map(([image, title, sub]) => <button className="work-card" key={image} onClick={() => setGallery({ image, title })} aria-label={`View ${title} photo`}><img src={`/images/${image}`} alt={title} loading="lazy" width="700" height="700" /><span className="work-overlay"><span><small>{sub}</small><strong>{title}</strong></span><span className="round-arrow"><Arrow /></span></span></button>)}</div><p className="gallery-footnote">Images from our existing website. Every property and installation is different.</p></div></section>

      <section className="faq-section" id="faqs"><div className="site-container faq-grid"><div><Eyebrow>A FEW THINGS YOU MIGHT BE WONDERING</Eyebrow><h2>Good questions.<br />Clear answers.</h2><p>Still have something on your mind?<br />We’re always happy to talk it through.</p><a href="tel:0466253396" className="text-link"><Phone size={16} /> {PHONE} <Arrow /></a></div><div><div className="faq-tabs" aria-label="Question categories">{['Getting started', 'The process', 'Rebates'].map(c => <button key={c} aria-pressed={c === faqCategory} className={c === faqCategory ? 'active' : ''} onClick={() => { setFaqCategory(c); setFaqOpen(faqs.find(f => f.category === c).q); }}>{c}</button>)}</div>{faqs.filter(f => f.category === faqCategory).map(f => { const id = `faq-${faqs.indexOf(f)}`; return <div key={f.q} className={`faq-item ${faqOpen === f.q ? 'open' : ''}`}><h3><button aria-expanded={faqOpen === f.q} aria-controls={id} onClick={() => setFaqOpen(faqOpen === f.q ? '' : f.q)}>{f.q}{faqOpen === f.q ? <Minus size={18} /> : <Plus size={18} />}</button></h3><div id={id} hidden={faqOpen !== f.q}><p>{f.a}</p></div></div>; })}</div></div></section>

      <section className="final-cta"><div className="site-container flex flex-wrap items-center justify-between gap-8"><div><Eyebrow light>LET’S MAKE YOUR HOME FEEL LIKE HOME</Eyebrow><h2>Your next chapter.<br />A little more comfortable.</h2></div><div><button className="btn btn-lime" onClick={() => openQuote()}>Get my free quote <Arrow /></button><p>No pressure. Just a conversation.</p></div></div><span className="cta-outline" aria-hidden="true">PF</span></section>
    </main>
    <footer><div className="site-container"><div className="footer-main"><div><Logo footer /><p>Thoughtful insulation.<br />Everyday comfort.</p><span className="footer-location"><MapPin size={14} /> Melbourne & surrounding Victoria</span></div><div><h3>MAKE YOURSELF AT HOME</h3><a href="#services">Our services</a><a href="#why-pf">Why PF Insulation</a><a href="#our-work">Our work</a><a href="#rebates">VEU information</a></div><div><h3>HERE TO HELP</h3><a href="#faqs">Common questions</a><button onClick={() => openQuote('Vacuum hire')}>Vacuum hire</button><a href="https://pfinsulation.com.au/blog-2-1" target="_blank" rel="noreferrer">Insulation journal <ArrowUpRight size={12} /></a><a href="https://www.instagram.com/insulation_removal_service/" target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={12} /></a></div><div><h3>LET’S TALK COMFORT</h3><a href="tel:0466253396" className="footer-phone">{PHONE} <Arrow /></a><a href={`mailto:${EMAIL}`}>{EMAIL}</a><button className="footer-quote" onClick={() => openQuote()}>Request a free quote <ArrowRight size={15} /></button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} PF Insulation. All rights reserved.</span><span>ABN 26 651 803 664</span><a href="#home">Back to top ↑</a></div></div></footer>
    <div className="mobile-sticky"><a href="tel:0466253396"><Phone size={17} /> Call our team</a><button onClick={() => openQuote()}>Get a free quote <Arrow /></button></div>
    {quote !== null && <QuoteDialog initialService={quote} onClose={() => setQuote(null)} />}
    {service && <Dialog onClose={() => setService(null)} label={service.name} className="service-modal"><img src={`/images/${service.image}`} alt={service.name} /><div className="service-modal-copy"><Eyebrow>{service.name}</Eyebrow><h2>{service.title}</h2><p>{service.details}</p><ul>{service.points.map(p => <li key={p}><Check size={17} />{p}</li>)}</ul><button className="btn btn-dark w-full" onClick={() => openQuote(service.name)}>Request a quote <Arrow /></button></div></Dialog>}
    {gallery && <Dialog onClose={() => setGallery(null)} label={gallery.title} className="gallery-modal"><img src={`/images/${gallery.image}`} alt={gallery.title} /><h2>{gallery.title}</h2></Dialog>}
  </>;
}
